// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Article", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("AuthorName").IsRequired().HasColumnType("text");
                b.Property<string>("Content").IsRequired().HasColumnType("text");
                b.Property<string>("CoverImageUrl").IsRequired().HasColumnType("text");
                b.Property<bool>("IsPublished").HasColumnType("boolean");
                b.Property<DateTime>("PublishedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Slug").IsRequired().HasColumnType("text");
                b.Property<string>("Summary").IsRequired().HasColumnType("text");
                b.Property<string>("Tags").IsRequired().HasColumnType("text");
                b.Property<string>("Title").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("Slug").IsUnique();
                b.ToTable("Articles");
            });

            modelBuilder.Entity("Backend.Models.TeamMember", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("AvatarUrl").IsRequired().HasColumnType("text");
                b.Property<string>("Bio").IsRequired().HasColumnType("text");
                b.Property<int>("DisplayOrder").HasColumnType("integer");
                b.Property<string>("Email").IsRequired().HasColumnType("text");
                b.Property<string>("FullName").IsRequired().HasColumnType("text");
                b.Property<string>("GitHub").HasColumnType("text");
                b.Property<bool>("IsActive").HasColumnType("boolean");
                b.Property<string>("LinkedIn").HasColumnType("text");
                b.Property<string>("Phone").HasColumnType("text");
                b.Property<string>("Role").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.ToTable("TeamMembers");
            });

            modelBuilder.Entity("Backend.Models.Track", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("AlbumTitle").IsRequired().HasColumnType("text");
                b.Property<string>("Artist").IsRequired().HasColumnType("text");
                b.Property<string>("AudioUrl").IsRequired().HasColumnType("text");
                b.Property<string>("CoverImageUrl").IsRequired().HasColumnType("text");
                b.Property<string>("Duration").IsRequired().HasColumnType("text");
                b.Property<string>("Genre").IsRequired().HasColumnType("text");
                b.Property<bool>("IsPublished").HasColumnType("boolean");
                b.Property<DateTime>("PublishedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Title").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.ToTable("Tracks");
            });

            modelBuilder.Entity("Backend.Models.Video", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("Category").IsRequired().HasColumnType("text");
                b.Property<string>("Description").IsRequired().HasColumnType("text");
                b.Property<bool>("IsPublished").HasColumnType("boolean");
                b.Property<DateTime>("PublishedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("ThumbnailUrl").IsRequired().HasColumnType("text");
                b.Property<string>("Title").IsRequired().HasColumnType("text");
                b.Property<string>("VideoUrl").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.ToTable("Videos");
            });
#pragma warning restore 612, 618
        }
    }
}
